package br.ufu.facom.network.dts.core.message;

public enum Service{
	ENTITY_REGISTER,
	ENTITY_MODIFY,
	ENTITY_UNREGISTER,
	WORKSPACE_LOOKUP,
	WORKSPACE_ADVERTISE,
	WORKSPACE_INVITION,
	WORKSPACE_ATTACH,
	WORKSPACE_DETACH,
	WORKSPACE_MODIFY,
	WORKSPACE_DELETE,
	WORKSPACE_PUBLISH,
	WORKSPACE_CREATE	
}